[package]
name = "lamport-sigs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
rand = "0.8.4"
num-bigint = { version = "0.2.2", features = ["rand"] }
